<a href="https://colab.research.google.com/github/rajbeer1/aks/blob/main/Assignment1_Quantum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Section 1

In [1]:
import numpy as np
import math

a = 1/math.sqrt(2)
b = 1/math.sqrt(2)

vector = np.array([a,b])

mag_sq = sum(k**2 for k in vector)
mag = math.sqrt(mag_sq)

if(np.isclose(mag,1)):
  print(" normalised")
else:
  print(" not normalised")

# printing length of vector
print("Length ", mag)


 normalised
Length  0.9999999999999999


## Section 2

In [2]:
def createVector():
    e = input("Enter elements separated by spaces: ")
    vector = list(float(item) for item in e.split())
    return vector

def isNormalised(vector):
    mag_sq = sum(k**2 for k in vector)
    mag = math.sqrt(mag_sq)
    return np.isclose(mag, 1)

def dotProduct(v1, v2):
    return np.dot(v1, v2)

def crossProduct(v1, v2):
    return np.cross(v1, v2)

def unitVector(vector):
    mag_sq = sum(k**2 for k in vector)
    mag = math.sqrt(mag_sq)
    return np.array(vector) / mag

v1 = createVector()
v2 = createVector()

if isNormalised(v1):
    print("normalised")
else:
    print(" not normalised")

print("Dot product:", dotProduct(v1, v2))
print("Cross product:", crossProduct(v1, v2))
print("Unit Vector:", unitVector(v1))

Enter elements separated by spaces: 5 6 8 
Enter elements separated by spaces: 6 7 8 
 not normalised
Dot product: 136.0
Cross product: [-8.  8. -1.]
Unit Vector: [0.4472136  0.53665631 0.71554175]


## Section 3

In [5]:
def createMatrix():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))

    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Enter elements for row {i + 1} separated by spaces: ").split()))
        matrix.append(row)

    return np.array(matrix)

matrix = createMatrix()

transpose = np.transpose(matrix)
determinant = np.linalg.det(matrix)
rank = np.linalg.matrix_rank(matrix)
trace = np.trace(matrix)
eigenvalues, eigenvectors = np.linalg.eig(matrix)
inverse = np.linalg.inv(matrix)

print("Original Matrix:")
print(matrix)

print("\nTranspose Matrix:")
print(transpose)

print("\nDeterminant of the Matrix:", determinant)

print("\nRank of the Matrix:", rank)

print("\nTrace of the Matrix:", trace)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

print("\nInverse of the Matrix:")
print(inverse)


Enter the number of rows: 3
Enter the number of columns: 3
Enter elements for row 1 separated by spaces: 12 55 67
Enter elements for row 2 separated by spaces: 34 56 78 
Enter elements for row 3 separated by spaces: 34 56 99 
Original Matrix:
[[12. 55. 67.]
 [34. 56. 78.]
 [34. 56. 99.]]

Transpose Matrix:
[[12. 34. 34.]
 [55. 56. 56.]
 [67. 78. 99.]]

Determinant of the Matrix: -25158.00000000001

Rank of the Matrix: 3

Trace of the Matrix: 167.0

Eigenvalues:
[172.59820145 -15.19246443   9.59426299]

Eigenvectors:
[[-0.4747758  -0.94244469 -0.39679842]
 [-0.58080053  0.30830131 -0.70243699]
 [-0.66125538  0.12941525  0.59087503]]

Inverse of the Matrix:
[[-0.04674457  0.0672947  -0.02138485]
 [ 0.02838063  0.04332618 -0.05334287]
 [ 0.         -0.04761905  0.04761905]]


## Section 4

In [6]:
def createCN():
    real = float(input("Enter the real part: "))
    img = float(input("Enter the imaginary part: "))

    return complex(real, img)

c1 = createCN()
c2 = createCN()

conjugate_num = np.conjugate(c1)

add = c1 + c2
subtract=  c1 - c2
multiply = c1 * c2

if c2 != 0:
    divide = c1/c2
else:
    divide = "Cannot divide by zero."

complex_as_vector = np.array([c1.real, c1.imag])

mag = np.abs(c1)

print("Complex Number:")
print(c1)

print("\nComplex Conjugate:")
print(conjugate_num)

print("\nAddition Result:")
print(add)

print("\nSubtraction Result:")
print(subtract)

print("\nMultiplication Result:")
print(multiply)

print("\nDivision Result:")
print(divide)

print("\nComplex Number as a 2D Vector:")
print(complex_as_vector)

print("\nMagnitude of the Complex Number:")
print(mag)


Enter the real part: 4
Enter the imaginary part: 5
Enter the real part: 4
Enter the imaginary part: 8
Complex Number:
(4+5j)

Complex Conjugate:
(4-5j)

Addition Result:
(8+13j)

Subtraction Result:
-3j

Multiplication Result:
(-24+52j)

Division Result:
(0.7-0.15j)

Complex Number as a 2D Vector:
[4. 5.]

Magnitude of the Complex Number:
6.4031242374328485
